# Generated by Django 2.1 on 2018-09-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('createdate', models.CharField(blank=True, db_column='createDate', max_length=10, null=True)),
                ('pickupdate', models.CharField(blank=True, db_column='pickupDate', max_length=10, null=True)),
                ('returndate', models.CharField(blank=True, db_column='returnDate', max_length=10, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.AutoField(db_column='storeID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('authenticationlevel', models.IntegerField(blank=True, db_column='authenticationLevel', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('carid', models.AutoField(db_column='carID', primary_key=True, serialize=False)),
                ('carmake', models.CharField(blank=True, db_column='carMake', max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('enginesize', models.CharField(blank=True, db_column='engineSize', max_length=20, null=True)),
                ('fuelsystem', models.CharField(blank=True, db_column='fuelSystem', max_length=255, null=True)),
                ('tankcapacity', models.CharField(blank=True, db_column='tankCapacity', max_length=60, null=True)),
                ('carpower', models.CharField(blank=True, db_column='carPower', max_length=20, null=True)),
                ('seatingcapacity', models.IntegerField(blank=True, db_column='seatingCapacity', null=True)),
                ('standardtransmission', models.CharField(blank=True, db_column='standardTransmission', max_length=20, null=True)),
                ('carbodytype', models.CharField(blank=True, db_column='carBodyType', max_length=20, null=True)),
                ('cardrivetype', models.CharField(blank=True, db_column='carDriveType', max_length=20, null=True)),
                ('carwheelbase', models.CharField(blank=True, db_column='carWheelBase', max_length=10, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
