# Generated by Django 2.1 on 2018-10-23 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Search', '0002_auto_20181023_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('createdate', models.CharField(blank=True, db_column='createDate', max_length=10, null=True)),
                ('pickupdate', models.CharField(blank=True, db_column='pickupDate', max_length=10, null=True)),
                ('returndate', models.CharField(blank=True, db_column='returnDate', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.AutoField(db_column='storeid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('authenticationlevel', models.IntegerField(blank=True, db_column='authenticationLevel', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('carid', models.AutoField(db_column='carid', primary_key=True, serialize=False)),
                ('carmake', models.CharField(blank=True, db_column='carmake', max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('enginesize', models.CharField(blank=True, db_column='engineSize', max_length=20, null=True)),
                ('fuelsystem', models.CharField(blank=True, db_column='fuelSystem', max_length=255, null=True)),
                ('tankcapacity', models.CharField(blank=True, db_column='tankCapacity', max_length=60, null=True)),
                ('carpower', models.CharField(blank=True, db_column='carPower', max_length=20, null=True)),
                ('seatingcapacity', models.IntegerField(blank=True, db_column='seatingCapacity', null=True)),
                ('standardtransmission', models.CharField(blank=True, db_column='standardTransmission', max_length=20, null=True)),
                ('carbodytype', models.CharField(blank=True, db_column='carBodyType', max_length=20, null=True)),
                ('cardrivetype', models.CharField(blank=True, db_column='carDriveType', max_length=20, null=True)),
                ('carwheelbase', models.CharField(blank=True, db_column='carWheelBase', max_length=10, null=True)),
                ('storeid', models.ForeignKey(blank=True, db_column='storeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Search.Store')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='carid',
            field=models.ForeignKey(blank=True, db_column='carid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Search.Vehicle'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickupstore',
            field=models.ForeignKey(blank=True, db_column='pickupstore', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_pickup', to='Search.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='returnstore',
            field=models.ForeignKey(blank=True, db_column='returnstore', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Search.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Search.User'),
        ),
    ]
